### ISSUE TITLE
Add setting for max shunting tasks

### ISSUE THREAD

**Issue by GamingCoookie** [fauxnik/dv-rolling-stock-ownership#17]
In the Ctrl+F10 menu, add a setting to choose how many(I guess as many as there are shunting track in the yard) or little (min 1) shunting tasks you want to do when loading or unloading. thanks

**Comment by monodop** [comment]
To be honest, I think it would be way nicer to remove shunting tasks all together. Instead, we can have jobs that are basically: "Load at station X, unload at station Y", and then let me shunt whichever way is most efficient for me. And as a result, it might be good to update the contracts to provide more pay to compensate for the lack of logistic haul and shunting jobs.

Right now, it's frustrating that the game will generate a job to deliver 3 cars of logs to sawmill, and then upon arriving I have to split the cars into multiple lanes after unloading, only to rejoin them immediately after so I can continue on. It just feels like unnecessary tedium imo.

**Comment by fauxnik** [comment]
@monodop, a few others, and I have been chatting about a job generation compatibility layer on discord. It should be capable of enabling this option in a more general manner, and opening the doors to other options too, like omitting shunting jobs altogether. It does require us to build it first though.

**Comment by fauxnik** [comment]
While not offering full control, #24 should help alleviate the underlying rationale a bit, I think.
