### ISSUE TITLE
[Bug] S282A spawns with hand brake even though it has none

### ISSUE THREAD

**Issue by ACH1980** [fauxnik/dv-rolling-stock-ownership#38]
As written in the title apparently the S282A (Front portion of the S282) spawns with Hand Brake applied, even though it has no hand brake making it impossible to release that brake. It's possible to drive with enough power, but it makes crazy sounds and doesn't drive very well.

Below is a picture of the brake gauge to show that the air brakes (train & independant) are properly set up (compressor started, tender connected, angle cocks at the ends closed):
![grafik](https://github.com/fauxnik/dv-rolling-stock-ownership/assets/39656381/df6a6fe6-7716-4be9-a0b2-af9e84e42474)

**Comment by ACH1980** [comment]
I guess it should be possible quite easily to just add an exception to this function:
```
private static IEnumerator CheckHandbrakeNextFrame(TrainCar trainCar)
	{
		yield return null;
		if (!trainCar.trainset.cars.Any(car => car.brakeSystem.brakeset.anyHandbrakeApplied))
		{
			trainCar.brakeSystem.handbrakePosition = 1f;
		}
	}

```
Apparently I was unable to find how the trainCar structure is structured, it's returned by this function, but that doesn't seem to be part of the mod itself: `CarSpawner.Instance.SpawnCar(prefab, destinationTrack, position, direction)`

**Comment by fauxnik** [comment]
You might try purchasing the tender first as a workaround until this is fixed.
